angular.module('project-seed.common', [
  'project-seed.common.services',
  'project-seed.filters',
  'project-seed.components',
  'project-seed.base-controller',
  'project-seed.config.constants' //generated by gulp-ng-constant
])

;
